<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>
<?php
$headTitle = 'Sample';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-6">
        <h3><?= $this->escapehtml($headTitle) ?></h3>
    </div>
    <div class="col-sm-6">
        <div class="text-right"><a href="/tutorial/sample/example" class="btn btn-info">Example</a></div>
    </div>
</div>
<?= $this->partial('partial/flash-message') ?>
<hr>
<p><?= $this->escapeHtml($this->date) ?></p>
<form action="/tutorial/sample" method="post">
    <input type="text" name="title">
    <input type="submit" value="Submit">
</form>
