<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>
<?php
$headTitle = 'Template';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-6">
        <h3><?= $this->escapehtml($headTitle) ?></h3>
    </div>
    <div class="col-sm-6">
        <div class="text-right"><a href="/tutorial/sample" class="btn btn-info">Sample</a></div>
    </div>
</div>
