<?php

/*class A
{
    public function greeting()
    {
        return 'Hello to You';
    }
}

class B
{
    public $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }
}


#$b = new B(new A);
#echo $b->a->greeting();

$di = new \Zend\Di\Di();
$b = $di->get('B');
echo $b->a->greeting();*/

?>




<?php
$headTitle = 'Tutorial';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapehtml($headTitle) ?></h3>
    </div>
</div>
<div><?= $this->escapeHtml($this->greetingService) ?></div>
<div><a href="/tutorial/sample">Sample</a></div>
<div><a href="/tutorial/product">Product</a></div>
