<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>
<?php
$headTitle = 'Product';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-6">
        <h3><?= $this->escapehtml($headTitle) ?></h3>
    </div>
    <div class="col-sm-6">
        <div class="float-right"><a href="/tutorial/product/add" class="btn btn-outline-primary">Add product</a></div>
    </div>
</div>
<hr>
<?= $this->partial('partial/flash-message') ?>
<div><a href="/tutorial/product/edit/12" class="btn btn-outline-primary">Edit product</a></div>
